language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t freddukker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true freddukker/docker-react npm run test
